# Generated by Django 3.1.4 on 2020-12-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Geography', 'Geography'), ('Economy', 'Economy'), ('Other', 'Other')], default='Other', max_length=32),
        ),
    ]
